JEEDOM_COM = ''
KNOWN_DEVICES = {}
INCLUDE_MODE = False
JEEDOM_SERIAL =''
CONFIG=None

FRAME_NUMBER = 0
ACK_NUMBER=1

RANDOMIZE_START = 0x42
RANDOMIZE_SEQ = 0xB8
FLAG = b"\x7E"
ESCAPE = b"\x7D"
XON = b"\x11"
XOFF = b"\x13"
SUBSTITUTE = b"\x18"
CANCEL = b"\x1A"
STUFF = 0x20
RESERVED = FLAG + ESCAPE + XON + XOFF + SUBSTITUTE + CANCEL

SEQUENCE = 0
EZSP_VERSION=4
